version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin   
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG_VERSION .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG_VERSION $IMAGE_REPO_NAME:$IMAGE_TAG_VERSION
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG_VERSION $IMAGE_REPO_NAME:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push --all-tags $IMAGE_REPO_NAME
  